# Use official Python image
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Copy requirements and install dependencies
COPY ./assistant/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY ./assistant ./

RUN crewai install



# Expose port and start the app
EXPOSE 8000
CMD ["uvicorn", "assistant.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload", "--app-dir", "src"]